application: pongroulette
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /soundfx
  static_dir: static/soundfx

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.+
  script: _go_app
